# Generated by Django 3.2.12 on 2023-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230128_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
