# Generated by Django 3.2.12 on 2023-01-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_choice_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='total_votes',
        ),
    ]
