# Generated by Django 4.1.5 on 2023-01-31 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20230131_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='choice',
            name='voted_by',
            field=models.ManyToManyField(through='app.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
